### ISSUE TITLE
Are there any plan to release a native build for ARM - MacOS M1 chip?

### ISSUE THREAD

**Issue by konglinghai123** [TravaOpenJDK/trava-jdk-8-dcevm#5]

**Comment by skybber** [comment]
Unfortunatelly not, may be there is a way how to do it using github actions.

**Comment by konglinghai123** [comment]
Can you give me a hint of what I should do？

**Comment by skybber** [comment]
You shoud fork this repo, and then look how the github actions are done in case of dcevm11 : https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/actions , I would also suggest following project: https://github.com/uraimo/run-on-arch-action , may be you can go through Trava forks, may be some already solved this problem. Let know how you get on.

**Comment by konglinghai123** [comment]
I downloaded the latest release "java8-openjdk-dcevm-osx.tar.gz" and install on my computer.The jvm can redefine the loaded class.It that means no promble?

**Comment by skybber** [comment]
Yes, then it's okay.

**Comment by konglinghai123** [comment]
Nice!
